### PR TITLE
Automate base image update process

### PR DESCRIPTION
**Pull request by ikstream**
Add a new make target 'update' to set the url and checksum in vagrant/template.json to the most recent version.
This PR should end monthly updates to the json file.

### CODE REVIEW

**Comment by ikstream** [comment]
I should probably use sha1 instead of md5 for checksum check.

**Comment by heichblatt** [comment]
Hi @ikstream,

sorry to keep you waiting so long. I had to think about this.

On the one hand, I see that this would automate an otherwise quite tedious task. On the other hand though, I'm not happy about the usage of weak checksum algorithms. SHA1 is unacceptable to me, MD5 is barely usable but should be avoided wherever possible. On the other hand we do not provide SHA256 sums, so MD5 is our best shot at the moment.

Ideally, the task of updating this repo with current ISO and checksums should be done by some kind of automation. I'll ask the team about how to achieve that.

I would like to merge this, but I don't think we want the `update` target to be run by default, i.e. when the user expects the target `build` to fulfill it's intended purpose, which is building what is defined in the repository. That would border on self-modifying code. If you could please add one more commit that achieves that, I'd be happy to merge.

Also let me thank you for your continued contributions to this repo.

Looking forward to hearing from you und viele Grüße aus Berlin. ;)

**Comment by ikstream** [comment]
If i understood your feedback right, this should address your concerns.
I would prefer a stronger checksum algorithm as well. 
I really appreciate that you made blackarch available on docker and vagrant.

Beste Grüße zurück

**Comment by heichblatt** [comment]
Awesome, thanks.

**Pull request merged**
